name: Job Scraper Automation

on:
  schedule:
    - cron: "0 9 * * *" # Runs daily at 9 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  scrape_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run job scraper
        run: python job_scraper.py
